### ISSUE TITLE
DF: User confusion: 2 pages with the same name. The fix is quick:)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#1288]
### Background / motivation

[Here](https://docs.oceanprotocol.com/rewards/user-guides) is the link to the DF rewards page, expanding the sidebar to include 7 sub-pages of "DF User Guides".

Screenshot of sidebar:
![Screenshot 2023-11-01 at 12 35 45](https://github.com/oceanprotocol/docs/assets/5305452/ddd32fcc-7471-4498-9746-e452cf5df96e)

Some datapoints:
- There are two pages with the name "Curate with Volume DF": (1) in the main section, and (2) in "DF User Guides" subsection. The first has "about" content, the second has "howto" content
-  ... "Predict with Challenge DF" ....

Problems:
1. User confusion: 2 pages with name "Curate with Volume DF"
2. User confusion: 2 pages with name "Predict with Challenge DF"
3. "Curate with Volume DF" page in main section does _not_ link its "about" counterpart. It should do so, and prominently. (FYO "Challenge DF" _does_ link, good.) 

### TODO

(There are heavier ways to fix this. Let's keep it lightweight and surgical.)

- [ ] For ["Curate with Volume DF" page in "DF User Guides" section](https://docs.oceanprotocol.com/rewards/user-guides/how-to-volumedf): Add "How to" or "Guide: " to its title such that overall title is "How to Curate with Volume DF" or "Guide: Curate with Volume DF".
- [ ] For ["Predict with Challenge DF" page in "DF User Guides" section]((https://docs.oceanprotocol.com/rewards/user-guides/how-to-challengedf): Add "How to" or "Guide:" to its title
- [ ] For ["Curate with Volume DF" page in main section](https://docs.oceanprotocol.com/rewards/df-volumedf): add a prominent link to the ["Curate with Volume DF" page in "DF User Guides" section.
