### ISSUE TITLE
DF: simplify structure to fix confusion of 'about' <> 'user guide' pages, more

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#1356]
### Background

The DF section has a parallel structure: For many topics (eg Volume DF), there's an "about" and a "user guide". They're in separate sections: "about" section, and then after all the "about" pages there's the "user guide" section. The content for each topic's "about" and for the "user guide" pages are quite good. Worth keeping. 

Also: there are kinda two 'about' READMEs (data-farming/README.md, data-farming/df-intro).

Also: there's a 'user guide' README (data-farming/user-guides/README.md file).

Screenshot: note the two groups of files.
![Screenshot 2023-11-05 at 08 40 14](https://github.com/oceanprotocol/docs/assets/5305452/bd825077-52d4-4d97-85e0-6208bd93134a)

### Issues

- 'about' & 'user guide' page for several topics aren't nearby, it's confusing
- having two 'about' READMEs is confusing
- the 'user guide' README is redundant with top-level 'about' READMEs
- the "df-" in front of many filenames is unneeded
- veocean.md also includes passive DF. The filename should include both.

### Towards a solution re about <> user-guide mirror

Options
1. flatten the hierarchy - remove the "user guide" group, and then put the pages in pairs one after the other (about -> user guide). Versions (1a): all flat, (1b): guide is a sub-page.
2. merge each into a single page. It's a fair bit of content, so have a TOC at the top.

Discussion:
- (2) will be easier for users to navigate, and for us to maintain, _if_ we have a TOC. Let's go for that.
- UPDATE: I tried (2) but TOCS didn't work so well. Let's try (1b)

### TODOs

(These are all in data-farming/ directory)

- [x] update SUMMARY.md to be the structure I want
- [x] rename df-veocean.md -> veocean-passivedf.md
- [x] rename df-volumedf.md -> volumedf.md
- [x] rename df-challengedf.md -> challengedf.md
- [x] rename & split df-emissions-apys.md -> ocean-missions.md & apys.md
- [x] rename df-faq.md -> faq.md
- [x] merge df-intro.md into README.md
- [x] merge user-guides/README.md into README.md
- [x] merge user-guides/how-to-veocean.md into veocean.md
- [x] merge user-guides/how-to-volumedf.md into volumedf.md
- [x] merge user-guides/how-to-delegate.md into volumedf.md
- [x] merge user-guides/how-to-challengedf.md into challengedf.md
- [x] move & rename user-guides/how-to-claim-rewards.md to claim-rewards.md
- [x] merge user-guides/how-to-estimate-apy.md into ocean-emissions.md & apys.md
- [x] add appropriate redirects for the above into .gitbook.yaml
- [x] ensure all references to old pagenames above in docs/ get changed to new location
- [x] get everything working end-to-end
- [x] Go from option (2) to (1a)
- [ ] tune / tighten content further by using [DF Main is Here](https://blog.oceanprotocol.com/ocean-data-farming-main-is-here-49c99602419e) blogpost as the baseline. (What other content can we chop?)
