### ISSUE TITLE
Low-hanging fruit for approachability

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#1407]
### Background

When people come to the docs, they encounter 8 boxes: Discover, User Guides, Developers, etc. Newcomers would typically click the first box "Discover". 

This takes them to the discover/README page "Why Ocean?" showing:

![Screenshot 2023-12-21 at 05 59 57](https://github.com/oceanprotocol/docs/assets/5305452/b9263fc4-b6af-4a2b-ab24-a1c5b758cbc7)

There are also a couple videos.

The next two pages are discover/explore "Explore", and discover/ocean-101 "Ocean 101". All three of these pages have large amounts of text. 

Then discover/basic-concepts "Basic Concepts" has many long paragraphs on blockchain, how Ocean uses blockchain, and OCEAN.

Then discover/wallets "Wallets" and discover/wallets/metamask-setup is generic content on using wallets & metamask.

### The opportunity

We can onboard people much better if we revamp the prime real estate of the first three pages, and the developer landing page. Here's how.

The first page is critical prime real estate. We can help onboard people better if they can quickly understand Ocean, and have quicklinks to the rest. So have:
- mission, how, and what of Ocean. 3 lines total, that's all.  
- teach them how it benefits _them_, where them = developer, data scientists, or OCEAN holders. 3 one-line bullets, that's all. With links.
- 1-2 other quick-links to other key docs sections
- finally: a link at the bottom that takes them to the next page, to help wayfinding. And that's _it_ for the first page.

The second page is also key real estate. In it, have:
- build mental model of conceptual "what"
  - one paragraph + image on data NFTs & datatokens. Expanding on "on- and off-ramp of data into defi
  - one paragraph + image on C2D
- link at bottom to next page

The next page can have:
- list "things you can do" by stakeholder
- link at bottom to next page

The pages on wallets, metamask setup, and manage your OCEAN can be in user guides section.

Many will jump to the developer page. That page is prime real estate for developers. We can onboard devs if they can quickly understand benefits to them, and how they might start using Ocean. This is how data scientists page is now. 
- So rework devs page to: dev benefits, how to start using. (Inspired by data scientists page)

Also: people really love OCEAN token but docs don't talk to it directly.

Also: the navigation "link to next page" should be across more of docs. And there should be a "back" link too.

Also: any larger pages should have a table of contents (TOC) at the top. It helps navigability, a lot. In addition to telling the user the precise content.

### TODOs

- [x] Revamp discover/ section basically like above
- [x] Add OCEAN page
- [x] Move the user guides on wallets, and basics, to "user guides"
- [x] ~~Add TOC to discover/ pages, main user-guide, wallets pages, network pages~~ Not possible with gitbook, despite it working on grip locally :(
- [x] Bonus: add "link to next page" in DF docs
- [x] Bonus: add "link to next page" in Predictoor docs
