### ISSUE TITLE
[Pdr] Reconcile pdr-related docs with docs.predictoor.ai 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#1426]
### Background

Traditionally we've had Predictoor docs at docs.oceanprotocol.com. But we're moving them to docs.oceanprotocol.com (WIP), being served up by `pdr-docs` repo. Epic: [pdr-docs#9](https://github.com/oceanprotocol/pdr-docs/issues/9).

Once that's live, we need to clean up predictoor-related docs in _this_ repo.

### Pre-requisite

docs.oceanprotocol.com must be live.

### TODOs

- [x] update predictoor/README.md to just (a) a one-liner of what predictoor is (b) "Predictoor docs are now at predictoor.ai" 
- [x] in SUMMARY.md, remove all but predictoor/README.md
- [x] in non-predictoor pages that point to predictoor docs, redirect to predictoor/README.md
- [x] update .gitbook.yaml: add redirects for each predictoor-related page to predictoor/README
- [x] in predictoor/ directory, delete all files except predictoor/README.md
- [x] in assets directory, delete all images used solely by predictoor
