### ISSUE TITLE
[DF] Tune docs for retired streams

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#1439]
## Context

What we've retired:
- Retired Passive DF & Volume DF on May 3, 2024. [#1436]( https://github.com/oceanprotocol/docs/issues/1436). [Blog](https://blog.oceanprotocol.com/passive-volume-data-farming-airdrop-has-completed-they-are-now-retired-6933520b5fcb).
- Retired Challenge DF in late 2023. [#1290](https://github.com/oceanprotocol/docs/issues/1290)

## TODOs
- [x] Mention that some DF streams have retired, and link to more info for each
- [x] In FAQ, answer "what about my locked veOCEAN?"
- [x] What other info that's in "Retired Passive DF & Volume DF" blog, that should be in docs?
