### ISSUE TITLE
All 3 "Storage Setup" pages reference Brizo lots, it should be Provider

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#721]
**Describe the bug**
Brizo is what "Provider" was called in Ocean V1 and V2. For V3, it got renamed.

However, the three "storage setup" pages in Ocean docs still refer to Brizo extensively.

**To Reproduce**

1. Go to https://docs.oceanprotocol.com/tutorials
2. In the left sidebar, scroll to "Storage setup" section. It has 3 sub-pages: 
  - Set Up Azure Storage - https://docs.oceanprotocol.com/tutorials/azure-for-brizo/
  - Set up Amazon S3 Stage - https://docs.oceanprotocol.com/tutorials/amazon-s3-for-brizo/
  - Set Up On-Premise Storage - https://docs.oceanprotocol.com/tutorials/on-premise-for-brizo/ 
3. If we go to any of these sub-pages, we'll see Brizo used extensively

**TODOs**

- [ ] Replace 'Brizo' with 'Provider' in the text
- [ ] The page urls replace 'brizo' with 'provider'
- [ ] Old page urls with 'brizo' auto-redirect to their 'provider' equivalent
