### ISSUE TITLE
Fix docs on did (oep7), ddo (oep8)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#722]
**Describe the bug**

We just moved OEP7 and OEP8 over from github.com/oceanprotocol/oeps to docs. Great! 

Now it's quite clear that several things are wrong or need improving. 

Here's a surgical list, in TODOs for (a) did (b) ddo (c) across both.

**(a) TODOs for did**
- [x] Rename top level from "oep" to "metadata", "Oep7" to "identifiers / dids", and "oep8" to "schema / ddos". Remove formal looking part at the top with authors version etc
- [x] remove most stuff in section "This specification is based..". Only keep ref to w3c.
- [x] Remove "change process" part 
- [x] Remove reference to provenance 
- [x] expand upon "In V3, the DID is based on the datatoken address" with one more sentence showing exactly how.
- [x] remove name of authors. Counter productive. Do for oep8 too
- [x] section that links to "You can find a complete real world example..." doesn't actually have that real world info anymore. So delete it
- [x] Broken link at : "You can find a complete example of a DDO"
- [x] Ensure that docs say metadata is stored on chain
- [x] Ensure that "cost" marked as obsolete. 
- [x] Toc "How to compute the integrity checks" is obsolete, remove it.
- [x] Ensure that Toc is consistent with actual contents 
- [x] Go through all links and make sure that they all work 

**(b) TODOs for oep8**

- [x] Rename overall thing away from oep8
- [x] Change "the file URLs, and they are stored in plaintext in the files object", since wrong.
- [x] Remove ref to oep11 and other oeps
- [x] Incorrect: "Typically can asset could be one of the following asset types: DataSet.. Algorithm". The first isn't just a file. And both should at least be more precise, ie use lowercase + courier font
- [x] Incorrect: "This list of attributes can’t be modified after creation, because these are considered as the metadata essence of the asset created. This information is used to calculate the unique checksum of the asse.."
- [x] Remove ref to squid
- [x] Ensure that "cost" marked as obsolete. 
- [x] Should refs to the "curation" attribute be removed?
- [x] Remove "change process" section 
- [x] Ensure that Toc is consistent with actual contents 
- [x] Go through all links and make sure that they all work 
- [x] Put into other issues. Create issues as needed.
  - [x] For v4, we can remove "datePublished", "dateCreated", ... --> Created #728 
  - [x] Make it easier to delineate required vs optional --> Created #721
  - [x] All 3 "Storage Setup" pages reference Brizo lots, it should be Provider -- >Created #721

**(c) TODOs - across both**
- [x] Ensure that the changes above make it into gaia-x testnet docs --> pushed to #730
- [x] Ensure that github.com/oceanprotocol/oeps sends the user to docs. DRY
