### ISSUE TITLE
Update DDO metadata schema for V4

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#728]
**Motivation**
Ocean metadata schema as of V3 is partly inherited from Ocean V1 and V2. Some fields should have never went over. 

Also, we've learned more since we released V3.

We're on a path to release Ocean V3. We can use it as an opportunity to refine metadata schema.

To start, we'll use this issue as a means to track 

Then we'll use the issue to actually remove them, as part of V4.

**TODOs**

- [ ] Document which attributes to remove, modify, or add. Include: thoroughly review each attribute, and ask whether to change
- [ ] Determine a plan to remove them. Need to coordinate among _many_ v4 branches, since many repos depend on the schema
- [ ] Execute on the plan

**Attributes to consider removing:**
- `metadata.main.cost`. Why: it's _always_ 1.0 datatokens to consume an asset. (And, don't confuse this with _price_ :)
- `metadata.main.datePublished`. Why: Redundant, since date published = date/time blockchain tx 
- `metadata.main.dateCreated`. Why: Useless, no one cares, what really matters is _when_ the claim is made, which is date published = date/time of blockchain tx
- `metadata.main.file.name` (filename) - there's already `url` (content url), so isn't `name` redundant?
- `metadata.main.fileindex` (index number starting from 0 of the file) - all the entries are _already_ given a list, which is ordered. Therefore redundant, error prone, not needed?
- `additionalInformation.categories` - redundant with `labels` attribute, and having both causes confusion. `labels` is more standard / more common.

**Attributes to add**
- Update DDO schema for user input data. (Initially documented by @alexcos20 as [OEPS#239](https://github.com/oceanprotocol/OEPs/issues/239)

**Comment by mihaisc** [comment]
**-- EDIT IN PROGRESS --**
I'll start with some suggestions/questions. I just took a ddo from the market. My other goal is to clarify each attribute so it can easily be moved into docs.
```
{
  // what is the purpose of this?
  "@context": "https://w3id.org/did/v1",
// this is the did, subject to change based on other issues/suggestions
  "id": "did:op:D0d7b9eb435CE2350BFAFa63d3D99860409B699d",
//date of creation
  "created": "2021-06-06T19:30:40Z",
// date of last update 
  "updated": "2021-06-10T11:57:18Z",
// this will be removed and moved to service
  "dataToken": "0xD0d7b9eb435CE2350BFAFa63d3D99860409B699d",
// what is the purpose of this structure, why not just move owner to root 
  "publicKey": [
    {
      "id": "did:op:D0d7b9eb435CE2350BFAFa63d3D99860409B699d",
      "type": "EthereumECDSAKey",
      "owner": "0xDF1c35c3d5178e9d98043b35a6737Bd861c191c9"
    }
  ],
// what is the purpose of this? the publicKey is just the did/id
  "authentication": [
    {
      "type": "RsaSignatureAuthentication2018",
      "publicKey": "did:op:D0d7b9eb435CE2350BFAFa63d3D99860409B699d"
    }
  ],
  "service": [ array of services],
  "proof": {
    "created": "2021-06-06T19:30:28Z",
    "creator": "0xDF1c35c3d5178e9d98043b35a6737Bd861c191c9",
    "type": "AddressHash",
    "signatureValue": "0x0e870c8dde468de839b55456604e3d81e0e4e5327ea2d9a5188f3b0f657d1abf"
  },
  "price": {
    "datatoken": 12.853142857142858,
    "ocean": 3141.9209598406305,
    "value": 123.30915106937083,
    "type": "pool",
    "exchange_id": "",
    "address": "0x9Ae5211780C379aD44d20917703546fa29Abf041",
    "pools": [
      "0x9Ae5211780C379aD44d20917703546fa29Abf041"
    ],
    "isConsumable": "true"
  },
  "isInPurgatory": "false",
  "dataTokenInfo": {
    "address": "0xD0d7b9eb435CE2350BFAFa63d3D99860409B699d",
    "name": "Dazzling Eel Token",
    "symbol": "DAZEEL-64",
    "decimals": 18,
    "cap": 1000
  },
  "chainId": 4,
  "accessWhiteList": [],
  "event": {
    "txid": "0x9fec545f2727dfc9b178c2b2eea4121509aa6f7321e12c96bfe4748b5bb4d662",
    "blockNo": 8739341,
    "from": "0xDF1c35c3d5178e9d98043b35a6737Bd861c191c9",
    "contract": "0xFD8a7b6297153397B7eb4356C47dbd381d58bFF4",
    "update": true
  }
}
```

Service : 
```

    {
      "type": "metadata",
      "attributes": {
        "status": {
          "isListed": true,
          "isRetired": false,
          "isOrderDisabled": false
        },
        "main": {
          "type": "dataset",
          "name": "European Fiscal Policy Implications on Retirement Schedules",
          "dateCreated": "2021-06-06T19:30:05Z",
          "author": "fadfsdfds",
          "license": "https://market.oceanprotocol.com/terms",
          "files": [
            {
              "contentLength": "",
              "contentType": "text/html; charset=UTF-8",
              "index": 0
            }
          ],
          "datePublished": "2021-07-25T20:20:53Z"
        },
        "additionalInformation": {
          "description": "Fee Simulator Dataset",
          "tags": [
            "sfsdfsdf"
          ],
          "termsAndConditions": true,
          "links": []
        },
        "encryptedFiles": "0x048cc9d2cd9bcc5315887c9b492c2e091db073e6a17351313fa3959f1c4947b63a0c68d325525b920ae8e0883b529de086cc154a399c8d5a77d56a8ec7a72fbfbbe7d4e83ad5b96059d6f975e9cceb51c3f25d414196a267c69c8c43c335e5fa5cc9b6cb3f7a01ddcec949081d040ea644f58af28d16794811774da7f635f547e8da9eca2cffce476b7e1b324fd9c42554bbeddca426748cd0938ee4b181217fdea3fcc34addf32f0f32d2538854eaacabe321fea10e44ab3ef37752e2c13710d4ed0d593525f1279645",
        "curation": {
          "rating": 0,
          "numVotes": 0,
          "isListed": true
        }
      },
      "index": 0
    },
    {
      "type": "access",
      "index": 1,
      "serviceEndpoint": "https://provider.rinkeby.oceanprotocol.com",
      "attributes": {
        "main": {
          "creator": "0xDF1c35c3d5178e9d98043b35a6737Bd861c191c9",
          "datePublished": "2021-06-06T19:30:05Z",
          "cost": "1",
          "timeout": 86400,
          "name": "dataAssetAccess"
        }
      }
    }
 ```

**Comment by kremalicious** [comment]
Duplicate of #690 but guess we abandon that other issue
