### ISSUE TITLE
Optimize docs on C2D

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/docs#808]
**Is your feature request related to a problem? Please describe.**

C2D docs are a bit scattered, some tactical things can really help. 

Content to draw from:
- There's now a nice C2D README in ocean.py (not linked from docs)
- In docs > concepts, there's a C2D "Overview" doc, it's crazy detailed especially for "concepts"
- In docs > tutorials, there's a whole C2D section with three pages
- Missing: stuff on docker registry 
- Missing: using GPU

**TODOs**

1. [x] New setup: docs > concepts _has_ a C2D "Overview" doc but it's 1/10 the size, and at the very top it links to the ocean.py README; and move the bulk of the content from docs > concepts > Overview page to a new "Overview" page in docs > tutorials > C2D. 
2. [x] break apart the new docs > tutorials > C2D "Overview" page into 2-3 pages
3. [x] add content on docker registry
4. [x] Update links in intro (https://deploy-preview-820--docs-oceanprotocol.netlify.app/concepts/compute-to-data/#datasets--algorithms)
5. [x] Compute-to-Data - new section Datasets and Algorithms
6. [x] Remove duplicate content and add Production deployment information

Removed:
add content on using GPU from todo
