### ISSUE TITLE
swagger reference issues

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/docs#87]
The important stuff works but syntax highlighting is a bit funky at the moment. As long as we don't use too much advanced features of Swagger spec, should be fine for our use case. As soon as we hit some limitation we need to revisit and update.

Collecting remaining issues on here:

- [ ] solve spec validation errors, see https://github.com/oceanprotocol/aquarius/issues/110
- [ ] output all request example fields, get inspiration from 
https://github.com/temando/open-api-renderer & https://github.com/aaronshaf/react-openapi
- [ ] make indentation and syntax highlighting consistent for all example fields
- [ ] remove hacky path reduction string manipulation (see https://github.com/oceanprotocol/brizo/issues/29 & https://github.com/oceanprotocol/aquarius/issues/114)
- [ ] automate spec file updates (#74)
- [ ] look into executing API calls (might not be possible until we have aquarius/brizo instance in the cloud somewhere)
- [ ] scroll spy for sidebar TOC (highlight active section heading)
- [ ] ...

**Comment by trentmc** [comment]
This is two years old. I'm closing it. Reopen if you think it's still relevant.
